 

export const MOCK_CATEGORIES = [
  { id: 'all', name: 'Todos', slug: 'all', icon: 'fa-grip' },
  { id: 'camisetas', name: 'Camisetas', slug: 'camisetas', icon: 'fa-shirt' },
  { id: 'moletons', name: 'Moletons', slug: 'moletons', icon: 'fa-user' },
  { id: 'calcas', name: 'Calças', slug: 'calcas', icon: 'fa-expand-alt' },
  { id: 'bones', name: 'Bonés', slug: 'bones', icon: 'fa-hat-cowboy' },
  { id: 'calcados', name: 'Calçados', slug: 'calcados', icon: 'fa-shoe-prints' },
  { id: 'acessorios', name: 'Acessórios', slug: 'acessorios', icon: 'fa-gem' },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Camiseta Oversized Urban Flow',
    brand: 'TRAJEZADA',
    category: 'camisetas',
    price: 149.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: false },
    ],
    colors: ['#0a0a0a', '#f5f5f5', '#ff3c00'],
    badges: ['new'],
    description: 'Camiseta oversized em algodão premium 100%. Caimento relaxed, ideal para o look streetwear do dia a dia. Impressão em silk alta qualidade.',
    sku: 'TRZ-001',
    stock: 24,
    featured: true,
  },
  {
    id: '2',
    name: 'Moletom Street Graffiti',
    brand: 'TRAJEZADA',
    category: 'moletons',
    price: 289.90,
    originalPrice: 349.90,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
      'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: false },
    ],
    colors: ['#2a2a2a', '#1a1a2e'],
    badges: ['sale'],
    description: 'Moletom com arte graffiti exclusiva. Tecido fleece pesado, 320g/m². Bolso canguru com zíper oculto. Edição especial assinada.',
    sku: 'TRZ-002',
    stock: 12,
    featured: true,
  },
  {
    id: '3',
    name: 'Calça Cargo Wide Leg',
    brand: 'TRAJEZADA',
    category: 'calcas',
    price: 319.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
    ],
    sizes: [
      { label: '36', available: true },
      { label: '38', available: true },
      { label: '40', available: true },
      { label: '42', available: true },
      { label: '44', available: false },
    ],
    colors: ['#1a1a1a', '#3d2b1f', '#2d4a3e'],
    badges: ['hot'],
    description: 'Calça cargo com corte wide leg. 6 bolsos funcionais, ajuste na cintura e barra. Ripstop resistente e confortável. O clássico streetwear repaginado.',
    sku: 'TRZ-003',
    stock: 18,
    featured: true,
  },
  {
    id: '4',
    name: 'Boné Snapback Classic',
    brand: 'TRAJEZADA',
    category: 'bones',
    price: 89.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80',
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80',
    ],
    sizes: [
      { label: 'Único', available: true },
    ],
    colors: ['#0a0a0a', '#ff3c00', '#f5f5f5'],
    badges: [],
    description: 'Boné snapback estruturado, aba plana. Bordado 3D da logo Trajezada. Ajuste universal com clipe plástico. Perfeito para finalizar o look.',
    sku: 'TRZ-004',
    stock: 50,
    featured: false,
  },
  {
    id: '5',
    name: 'Tenis Urban Runner Low',
    brand: 'TRAJEZADA',
    category: 'calcados',
    price: 459.90,
    originalPrice: 549.90,
    discount: 16,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    ],
    sizes: [
      { label: '38', available: true },
      { label: '39', available: true },
      { label: '40', available: false },
      { label: '41', available: true },
      { label: '42', available: true },
      { label: '43', available: true },
      { label: '44', available: false },
    ],
    colors: ['#f5f5f5', '#0a0a0a'],
    badges: ['sale', 'hot'],
    description: 'Tênis low-top com solado vulcanizado. Cabedal em lona premium, palmilha EVA de alta absorção. Colaboração exclusiva com artista urbano local.',
    sku: 'TRZ-005',
    stock: 8,
    featured: true,
  },
  {
    id: '6',
    name: 'Camiseta Tie-Dye Distorted',
    brand: 'TRAJEZADA',
    category: 'camisetas',
    price: 169.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: false },
      { label: 'GG', available: true },
    ],
    colors: [],
    badges: ['limited'],
    description: 'Camiseta tie-dye feita à mão. Cada peça é única com variações naturais do tingimento. Edição limitada de 100 unidades numeradas.',
    sku: 'TRZ-006',
    stock: 6,
    featured: false,
  },
  {
    id: '7',
    name: 'Mochila Street Pack',
    brand: 'TRAJEZADA',
    category: 'acessorios',
    price: 239.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
      'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=600&q=80',
    ],
    sizes: [
      { label: 'Único', available: true },
    ],
    colors: ['#1a1a1a', '#ff3c00'],
    badges: ['new'],
    description: 'Mochila 25L em lona impermeável. Compartimento para notebook 15", saída USB interna, múltiplos bolsos. Alças ergonômicas acolchoadas.',
    sku: 'TRZ-007',
    stock: 20,
    featured: false,
  },
  {
    id: '8',
    name: 'Corta-Vento Windbreaker',
    brand: 'TRAJEZADA',
    category: 'moletons',
    price: 399.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
      'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: false },
      { label: 'G', available: true },
      { label: 'GG', available: true },
    ],
    colors: ['#0a0a0a', '#1a3a2a', '#1a1a3a'],
    badges: ['new'],
    description: 'Corta-vento com revestimento impermeável. Capuz ajustável, bolsos com zíper YKK, refletivos nas costuras. Estampa full-print exclusiva.',
    sku: 'TRZ-008',
    stock: 15,
    featured: true,
  },
  {
    id: '9',
    name: 'Regata Box Logo',
    brand: 'TRAJEZADA',
    category: 'camisetas',
    price: 99.90,
    originalPrice: 129.90,
    discount: 23,
    images: [
      'https://images.unsplash.com/photo-1565693413579-8ff3fdc1b03b?w=600&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
    ],
    colors: ['#0a0a0a', '#f5f5f5', '#ff3c00', '#ffd600'],
    badges: ['sale'],
    description: 'Regata estampada com box logo Trajezada. Malha dry-fit respirável, ideal para dias quentes ou academia. Corte amplo.',
    sku: 'TRZ-009',
    stock: 35,
    featured: false,
  },
  {
    id: '10',
    name: 'Cinto Tático Urban',
    brand: 'TRAJEZADA',
    category: 'acessorios',
    price: 69.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    ],
    sizes: [
      { label: 'P/M', available: true },
      { label: 'G/GG', available: true },
    ],
    colors: ['#1a1a1a', '#8b7355'],
    badges: [],
    description: 'Cinto tático em nylon resistente com fivela de metal. Largura 3,8cm, comprimento ajustável. Clássico streetwear militar.',
    sku: 'TRZ-010',
    stock: 30,
    featured: false,
  },
  {
    id: '11',
    name: 'Jaqueta Jeans Destroyed',
    brand: 'TRAJEZADA',
    category: 'moletons',
    price: 499.90,
    originalPrice: 599.90,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
      'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&q=80',
    ],
    sizes: [
      { label: 'P', available: false },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: false },
    ],
    colors: ['#3d4f6a', '#1a1a1a'],
    badges: ['sale', 'limited'],
    description: 'Jaqueta jeans com efeito destroyed. Patches bordados, lavagem stone diferenciada. Forro interno removível. Peça statement para o seu guarda-roupa.',
    sku: 'TRZ-011',
    stock: 7,
    featured: true,
  },
  {
    id: '12',
    name: 'Meias Pack Street (3 pares)',
    brand: 'TRAJEZADA',
    category: 'acessorios',
    price: 59.90,
    originalPrice: null,
    discount: null,
    images: [
      'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80',
    ],
    sizes: [
      { label: '36-39', available: true },
      { label: '40-43', available: true },
      { label: '44-46', available: true },
    ],
    colors: ['#0a0a0a'],
    badges: [],
    description: 'Kit com 3 pares de meias streetwear. Designs exclusivos Trajezada. Cano médio, 80% algodão. Um item essencial do streetwear.',
    sku: 'TRZ-012',
    stock: 60,
    featured: false,
  },
];
